name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - name: Create .env
        run: echo 'PORT=${{ secret.PORT }}' > .env

      - name: Run build
        run: docker-compose up -d
